version: "3.9"  # optional since v1.27.0
services:
  client:
    container_name: test-vm-client
    image: R9-fileserver
    command: bash -c "cd /R9-fileserver && cargo +nightly test"
    cap_add:
      - SYS_ADMIN
    # Allows calling mount under linux
    privileged: true
        
